# Generated by Django 4.2.6 on 2024-06-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viruta',
            fields=[
                ('viruta_ndx', models.AutoField(primary_key=True, serialize=False)),
                ('dt_126_2_densidad_soda_c', models.IntegerField(blank=True, db_column='DT_126_2_DENSIDAD_SODA_C', null=True)),
                ('fic_126_104_flujo_salmuera', models.IntegerField(blank=True, db_column='FIC_126_104_FLUJO_SALMUERA', null=True)),
                ('fit_104_101_flujo_less', models.IntegerField(blank=True, db_column='FIT_104_101_FLUJO_LESS', null=True)),
                ('fit_126_1a_flujo_pko', models.IntegerField(blank=True, db_column='FIT_126_1A_FLUJO_PKO', null=True)),
                ('fit_126_1b_flujo_stearine', models.IntegerField(blank=True, db_column='FIT_126_1B_FLUJO_STEARINE', null=True)),
                ('fit_126_1c_flujo_sebo', models.IntegerField(blank=True, db_column='FIT_126_1C_FLUJO_SEBO', null=True)),
                ('fit_126_2_flujo_soda_c', models.IntegerField(blank=True, db_column='FIT_126_2_FLUJO_SODA_C', null=True)),
                ('fit_126_3_flujo_agua', models.IntegerField(blank=True, db_column='FIT_126_3_FLUJO_AGUA', null=True)),
                ('ji_204_101_corriente_atz', models.IntegerField(blank=True, db_column='JI_204_101_CORRIENTE_ATZ', null=True)),
                ('pit_126_10_presion_reactor', models.IntegerField(blank=True, db_column='PIT_126_10_PRESION_REACTOR', null=True)),
                ('pit_204_2_vacio_atz', models.IntegerField(blank=True, db_column='PIT_204_2_VACIO_ATZ', null=True)),
                ('pit_204_10_presion_jabon_y_entrada_atz', models.IntegerField(blank=True, db_column='PIT_204_10_PRESION_JABON_Y_ENTRADA_ATZ', null=True)),
                ('pit_204_50_presion_extrusor', models.IntegerField(blank=True, db_column='PIT_204_50_PRESION_EXTRUSOR', null=True)),
                ('tt_126_2_temp_soda_caustica', models.IntegerField(blank=True, db_column='TT_126_2_TEMP_SODA_CAUSTICA', null=True)),
                ('tt_126_5_temp_soda_c_agua_e_intercambiador', models.IntegerField(blank=True, db_column='TT_126_5_TEMP_SODA_C_AGUA_E_INTERCAMBIADOR', null=True)),
                ('tt_126_6_temp_grasas_intercambiador', models.IntegerField(blank=True, db_column='TT_126_6_TEMP_GRASAS_INTERCAMBIADOR', null=True)),
                ('tt_126_9_temp_reactor', models.IntegerField(blank=True, db_column='TT_126_9_TEMP_REACTOR', null=True)),
                ('tt_126_18_temp_salida_turbo', models.IntegerField(blank=True, db_column='TT_126_18_TEMP_SALIDA_TURBO', null=True)),
                ('tt_206_1_temp_salida_condensador', models.IntegerField(blank=True, db_column='TT_206_1_TEMP_SALIDA_CONDENSADOR', null=True)),
                ('tt_206_2_temp_entrada_condensador', models.IntegerField(blank=True, db_column='TT_206_2_TEMP_ENTRADA_CONDENSADOR', null=True)),
                ('tt_206_3_temp_agua_enfriamiento', models.IntegerField(blank=True, db_column='TT_206_3_TEMP_AGUA_ENFRIAMIENTO', null=True)),
                ('t_stamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'viruta',
                'managed': False,
            },
        ),
    ]
