# Generated by Django 4.2.6 on 2024-02-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Secadores', '0002_alter_linea1_options_alter_linea6_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linea7',
            old_name='presion_interc3_pic200_2',
            new_name='presioninterc3_pic200_2',
        ),
    ]
