# Generated by Django 4.2.6 on 2024-02-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Secadores', '0003_rename_presion_interc3_pic200_2_linea7_presioninterc3_pic200_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linea6',
            old_name='presionjabonatz_pit200_3',
            new_name='presionjabonatm_pit200_3',
        ),
    ]
