# Generated by Django 4.2.6 on 2024-03-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Secadores', '0004_rename_presionjabonatz_pit200_3_linea6_presionjabonatm_pit200_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linea7',
            old_name='vacioatz_pit200_4',
            new_name='vacioatmz_pit200_4',
        ),
    ]
