# Generated by Django 4.2.6 on 2023-10-10 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SKUModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('humedad_objetiva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TamuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso_obtenido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad_objetiva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad_obtenida', models.DecimalField(decimal_places=2, max_digits=5)),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tamu.areamodel')),
                ('skuID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tamu.skumodel')),
            ],
        ),
        migrations.CreateModel(
            name='LineaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tamu.areamodel')),
            ],
        ),
    ]
