# Generated by Django 4.2.6 on 2024-02-26 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('areaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.areamodel')),
            ],
        ),
        migrations.CreateModel(
            name='LineaSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5, null=True)),
                ('areaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.areamodel')),
            ],
        ),
        migrations.CreateModel(
            name='SKUModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoSKU', models.CharField(max_length=30, null=True, unique=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('humedad_objetiva', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('peso_objetivo', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('temperatura_objetiva', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tamu.areamodel')),
            ],
        ),
    ]
