# Generated by Django 4.2.6 on 2023-11-22 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('areaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.areamodel')),
            ],
        ),
        migrations.CreateModel(
            name='LineaSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5, null=True)),
                ('areaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.areamodel')),
            ],
        ),
        migrations.CreateModel(
            name='SKUModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('humedad_objetiva', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('peso_objetivo', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('temperatura_objetiva', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tamu.areamodel')),
            ],
        ),
        migrations.CreateModel(
            name='TamuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_objetivo', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('peso_obtenido', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('humedad_objetiva', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('humedad_obtenida', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('temperatura_objetiva', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('temperatura_obtenida', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('areaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.areamodel')),
                ('lineaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.linea')),
                ('seccionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.lineaseccion')),
                ('skuID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.skumodel')),
            ],
        ),
        migrations.AddField(
            model_name='linea',
            name='lado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.lineaseccion'),
        ),
    ]
