# Generated by Django 4.2.6 on 2024-02-26 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tamu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_objetivo', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('peso_obtenido', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('humedad_objetiva', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('humedad_obtenida', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('temperatura_objetiva', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('temperatura_obtenida', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('areaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.areamodel')),
                ('lineaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.linea')),
                ('quien_registra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seccionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.lineaseccion')),
                ('skuID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.skumodel')),
            ],
        ),
    ]
