# Generated by Django 4.2.6 on 2023-10-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tamu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='skumodel',
            name='areaId',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Tamu.areamodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamumodel',
            name='lineaId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tamu.lineamodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamumodel',
            name='temperatura_obtenida',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamumodel',
            name='valores_registrados',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='areamodel',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lineamodel',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skumodel',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skumodel',
            name='humedad_objetiva',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='skumodel',
            name='peso_objetivo',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='lineamodel',
            name='seccionId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tamu.lineaseccion'),
            preserve_default=False,
        ),
    ]
