# Generated by Django 4.2.6 on 2024-01-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamu', '0002_remove_linea_lado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamumodel',
            name='humedad_obtenida',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tamumodel',
            name='peso_obtenido',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tamumodel',
            name='temperatura_obtenida',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
