# Generated by Django 4.2.6 on 2023-10-13 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tamu', '0002_lineaseccion_skumodel_areaid_tamumodel_lineaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineamodel',
            name='seccionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.lineaseccion'),
        ),
    ]
