# Generated by Django 4.2.6 on 2023-10-17 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tamu', '0003_alter_lineamodel_seccionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineamodel',
            name='seccionId',
        ),
        migrations.AddField(
            model_name='lineaseccion',
            name='areaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.areamodel'),
        ),
    ]
