# Generated by Django 4.2.6 on 2024-03-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamu', '0003_skumodel_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skumodel',
            name='humedad_objetiva',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='skumodel',
            name='peso_objetivo',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='skumodel',
            name='temperatura_objetiva',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
