# Generated by Django 4.2.6 on 2024-01-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamu', '0005_alter_tamumodel_humedad_obtenida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamumodel',
            name='humedad_obtenida',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tamumodel',
            name='peso_obtenido',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tamumodel',
            name='temperatura_obtenida',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
