# Generated by Django 4.2.6 on 2023-10-23 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tamu', '0007_alter_skumodel_humedad_objetiva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamumodel',
            name='areaId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.areamodel'),
        ),
        migrations.AlterField(
            model_name='tamumodel',
            name='humedad_objetiva',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tamumodel',
            name='humedad_obtenida',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tamumodel',
            name='lineaId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.lineamodel'),
        ),
        migrations.AlterField(
            model_name='tamumodel',
            name='peso_objetivo',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tamumodel',
            name='peso_obtenido',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tamumodel',
            name='seccionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.lineaseccion'),
        ),
        migrations.AlterField(
            model_name='tamumodel',
            name='skuID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamu.skumodel'),
        ),
        migrations.AlterField(
            model_name='tamumodel',
            name='temperatura_objetiva',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tamumodel',
            name='temperatura_obtenida',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
