# Generated by Django 4.2.6 on 2023-10-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamu', '0008_alter_tamumodel_areaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamumodel',
            name='humedad_objetiva',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tamumodel',
            name='peso_objetivo',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tamumodel',
            name='temperatura_objetiva',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
    ]
