# Generated by Django 4.2.6 on 2024-01-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('us_entrega', models.CharField(max_length=50, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now=True)),
                ('fecha_fin', models.DateTimeField(auto_now=True)),
                ('alcalinidad', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('cloruro', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('activo', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('otros_analisis', models.CharField(max_length=100, null=True)),
                ('us_operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usr_operador', to='Laboratorio.user')),
                ('us_recibe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usr_recibe', to='Laboratorio.user')),
            ],
        ),
    ]
