# Generated by Django 4.2.6 on 2024-01-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0002_user_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_registro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
