# Generated by Django 4.2.6 on 2024-01-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0003_user_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='activo',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='alcalinidad',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='cloruro',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='humedad',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='otros_analisis',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
