# Generated by Django 4.2.6 on 2024-01-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0004_alter_analisis_activo_alter_analisis_alcalinidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisis',
            name='us_operador',
        ),
    ]
