# Generated by Django 4.2.6 on 2024-01-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0005_remove_analisis_us_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
