# Generated by Django 4.2.6 on 2024-01-31 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0006_alter_analisis_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='estado',
            field=models.CharField(choices=[('en proceso', 'Pendiente'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado')], default='en proceso', max_length=20),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='us_entrega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usr_entrega', to='Laboratorio.user'),
        ),
    ]
