# Generated by Django 4.2.6 on 2024-02-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0007_alter_analisis_estado_alter_analisis_us_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='solicitud_total',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='estado',
            field=models.CharField(choices=[('en proceso', 'Pendiente'), ('finalizado', 'Finalizado'), ('cancelado', 'Rechazado')], default='en proceso', max_length=20),
        ),
    ]
