# Generated by Django 4.2.6 on 2024-02-05 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0008_analisis_solicitud_total_alter_analisis_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
